### PR TITLE
Forest Fire Mapping using Sentinel 2

### PR DESCRIPTION
**Pull request by Pratichhya**
In this notebook, we showcase the process up to the calculation of the difference of NDVI for pre and post-fire data using sentinel-2 discussed in the [paper](https://www.mdpi.com/2072-4292/12/13/2162#). 

Furthermore, we also tried the NBR-based approach, which was mentioned in the paper but not implemented.

### CODE REVIEW

**Comment by Pratichhya** [comment]
@soxofaan could you please provide your feedback when available?

**Comment by Pratichhya** [comment]
a kind reminder

**Comment by jdries** [comment]
- [ ] Consider putting this generic sample under openeo community samples?
- [ ] Load SCL as a separate cube. OpenEO can then load only the other bands for areas that are not masked.
- [ ] Consider using synchronous calls instead of batch all the time? Timings seem to allow it?

**Comment by Pratichhya** [comment]
> * [x]  Consider putting this generic sample under openeo community samples?

opened a new PR in the community samples repo (https://github.com/Open-EO/openeo-community-examples/pull/20)

> * [x]  Load SCL as a separate cube. OpenEO can then load only the other bands for areas that are not masked.

Created a separate datacube with SCL band.

> * [x]  Consider using synchronous calls instead of batch all the time? Timings seem to allow it?

Yes, used synchronous approach

> * [x]  NBR index support is built into python client normally, so you can use the short form to compute it.

used the `compute_indices` from [Awesome Spectral Indices](https://awesome-ee-spectral-indices.readthedocs.io/en/latest/index.html)

**Pull request closed without merging**
