### PR TITLE
NDVI-based approach to study Landslide areas

### PR DESCRIPTION
**Pull request by Pratichhya**
Research indicates that NDVI can play a crucial role in identifying landslide zones. While an advanced workflow is possible, this notebook opts for a simple approach using dNDVI and applying a threshold to the result to detect areas where landslides occurred.

### CODE REVIEW

**Comment by soxofaan** [comment]
Interesting notebook

> simple approach using dNDVI and

is that "dNDVI" a commoly known term in EO or is it a typo? I haven't seen this before.

> from openeo.processes import min, max, mean
> import numpy as np

I don't think these imports are used, so can be dropped:


> openeo.connect("openeo.dataspace.copernicus.eu/")

drop that final "/"

> `# load pre Sentinel2 collection`

In general I would put all these code comments just in jupyter text cells, which looks nicer

> spatial_extent={
        "west": 13.882567409197492,
        "south": 40.7150627793427,
        "east": 13.928593792166282,
        "north": 40.747050251559216,
    },

I would define a `spatial_extent` variable and reuse it in both `load_collection`s. 

> plt.imshow(img > 0.4, vmin=0, vmax=1)

I'm confused: the `img > 0.4`  is a binary image, but I see colors in the image, and you add a colorbar. Where do these colors come from and what do they mean?
Side note: the x an y labels are currently meaningless, can you put real lonlat coords there?


Another question: in the resulting image you indeed see this landslide structure in the red ellipse. However there are a lot of other highlighted pixels in even larger clusters, are these landslides too? And if not, can you give a comment about what they are about instead?

**Comment by Pratichhya** [comment]
> I think it's also worth to explain a bit how `pre - post > 0.4` works: detecting a drop of more than 0.4 in NDVI value. To me, it would be more intuitive to have it expressed inversely as `post - pre < -0.4` or `post < pre - 0.4`

Updated the notebook with the suggested method and additional text on false positives.

**Comment by Pratichhya** [comment]
a kind reminder

**Comment by Pratichhya** [comment]
As suggested (generic sample under openeo community samples), this PR is migrated to https://github.com/Open-EO/openeo-community-examples/pull/21

**Pull request closed without merging**
