### PR TITLE
Add Sentinel 1 ARD example

### PR DESCRIPTION
**Pull request by Pratichhya**
Create a page on the options to generate S1 ARD data using the tools from CDSE #178 in the documentation.

This notebook is the replicated version of [Radar ARD](https://github.com/openEOPlatform/sample-notebooks/blob/main/openEO%20Platform%20-%20Radar%20ARD.ipynb) example available for openEO platform.

However, due to the unavailability of terrain coefficient for performing SAR backscattering, an additional step of including SAR backscattering with gamma0-ellipsoid is done. 

Therefore, I am aware and believe that in the absence of terrain information, an ellipsoidal Earth model can be used to define the reference areas. But, this may lead to some inaccuracy in the normalised backscatter.

Please suggest me or let me know if a different approach needs to be taken into consideration.

### CODE REVIEW

**Review by jdries — CHANGES_REQUESTED** [review]
- ard_normalized_radar_backscatter does not really work on cdse and you normally do not apply it after sar_backscatter, so please remove that
- use sigma0-ellipsoid here, not to sure about gamma0
- use the short form of executing batch jobs, we want to show that we do not require lots of lines of code
- you do not need format="netCDF", openEO client guesses that from the .nc extentions
- you do not need explicit save_result
- at the bottom, it mentions other coefficients, most of them are not yet supported on CDSE

**Comment by Pratichhya** [comment]
> * ard_normalized_radar_backscatter does not really work on cdse and you normally do not apply it after sar_backscatter, so please remove that
> * use sigma0-ellipsoid here, not to sure about gamma0
> * use the short form of executing batch jobs, we want to show that we do not require lots of lines of code
> * you do not need format="netCDF", openEO client guesses that from the .nc extentions
> * you do not need explicit save_result
> * at the bottom, it mentions other coefficients, most of them are not yet supported on CDSE

Noted and updated 😄

**Review by jdries — CHANGES_REQUESTED** [review]
maybe just drop the optional batch job execution entirely, we shouldn't put two ways of running jobs in each notebook, it makes it overly long and distracts from the actual point

can you also try if orbitDirection can be replaced with sat:orbit_state? The latter is the official stac property for this.

**Comment by Pratichhya** [comment]
> sat:orbit_state

Included only synchronous approach and tried with and replaced orbitDirection with sat:orbit_state.

**Review by jdries — CHANGES_REQUESTED** [review]
Almost there!
the titles in the plot still say gamma0, while it's now sigma0

In load_collection, can you inline a few properties like temporal extent and collection name?
Our message to users is that you can do things with few lines of code. So where possible, we should go for shorter forms. Note that this doesn't mean we should produce cryptic, unreadable statements, but declaring variables that are basically used in only one place feels unnecessary and for me even reduces readability.

**Comment by Pratichhya** [comment]
> Almost there! the titles in the plot still say gamma0, while it's now sigma0
> 
> In load_collection, can you inline a few properties like temporal extent and collection name? Our message to users is that you can do things with few lines of code. So where possible, we should go for shorter forms. Note that this doesn't mean we should produce cryptic, unreadable statements, but declaring variables that are basically used in only one place feels unnecessary and for me even reduces readability.

Ahh that was my mistake, sorry didn't noticed. Updated. Also let me know more changes needed, I can miss sometimes by overlooking

**Comment by Pratichhya** [comment]
@jdries, should additional changes be made to this PR?

**Comment by Pratichhya** [comment]
> Hi @Pratichhya , only remaining problem is that it links back to openeo.cloud for more info, while we want to provide self-contained documentation here.
> 
> > This notebook has been duplicated from an existing sample processing pipeline for Radar ARD on the openEO platform. In this instance, we aim to showcase it with the Copernicus Data Space Ecosystem backend.
> > For more information [click here](https://docs.openeo.cloud/usecases/ard/).ess

Updated the notebook with details contained within and removed the linking to the openeo.cloud.

**Comment by Pratichhya** [comment]
@jdries a simple reminder

**Review by jdries — APPROVED** [review]

**Comment by jdries** [comment]
thanks, fine to merge for me!

**Pull request merged**
