### PR TITLE
Fix xcube-sh install command in markdown

### PR DESCRIPTION
**Pull request by Kampen1988**
Should fix the issue reported in this [Jira ticket](https://jira.cloudferro.com/browse/CDSE-1077) @Pratichhya

### CODE REVIEW

**Comment by Pratichhya** [comment]
I don't think this still solves the issue Max.

The error is due to "---" as if you observe our qmd pages in documentation; they include these as yaml content. So when rendering these notebooks within the usecase.qmd it is trying to render in such a way as:



---
title: "Usecase"
content: 
     href: just_an_example.ipynb that also includes --- and ---
       
---

**Comment by Kampen1988** [comment]
Thanks for the pointers, @Pratichhya! I exchanged the horizontal line operators from "---" to "***". Please let me know if this solves the issue.

**Comment by Pratichhya** [comment]
Thnaks Max, it seems to solve the issue with the changes. Could you please merge it before I push the changes to documentation?

**Comment by Pratichhya** [comment]
> Thnaks Max, it seems to solve the issue with the changes. Could you please merge it before I push the changes to documentation?

cc @KanerLev

**Pull request merged**
